[@ww.textfield labelKey="com.zend.zendserver.plugins.zs_url" name="zs_url" required='true'/]
[@ww.textfield labelKey="com.zend.zendserver.plugins.api_key" name="api_key" required='true'/]
[@ww.textfield labelKey="com.zend.zendserver.plugins.api_secret" name="api_secret" required='true'/]
[@ww.textfield labelKey="com.zend.zendserver.plugins.base_url" name="base_url" required='true'/]
[@ww.textfield labelKey="com.zend.zendserver.plugins.app_name" name="app_name" required='true'/]
[@ww.textfield labelKey="com.zend.zendserver.plugins.zsversion" name="zsversion" required='true'/]