[@ww.label labelKey="API Key" name="api_key"/]
[@ww.label labelKey="API Secret" name="api_secret"/]
[@ww.label labelKey="Zend Server URL" name="url"/]
[@ww.label labelKey="Application Base URL" name="base_url"/]
[@ww.label labelKey="Application Name" name="app_name"/]
[@ww.label labelKey="Zend Server Version" name="zsversion"/]