[@ww.textfield labelKey="Zend Server URL" name="zs_url" required='true'/]
[@ww.textfield labelKey="API Key" name="api_key" required='true'/]
[@ww.textfield labelKey="API Secret" name="api_secret" required='true'/]
[@ww.textfield labelKey="Application Base URL" name="base_url" required='true'/]
[@ww.textfield labelKey="Application Name" name="app_name" required='true'/]
[@ww.textfield labelKey="Zend Server Version" name="zsversion" required='true'/]
[@ww.textfield labelKey="Custom zs-client options" name="custom_options" required='false'/]
[@ww.textfield labelKey="Amount of retries for status check" name="retry" required='true'/]
[@ww.textfield labelKey="Wait time (sec) between retry iterations" name="waittime" required='true'/]
[@ww.checkbox labelKey="Rollback automatically in case of a deployment error" name="rollback"/]