[@ww.textfield labelKey="com.zend.zendserver.plugins.zs_url" name="zs_url" required='true'/]
<small>The Zend Server URL. E.g. http://localhost:10081</small>
[@ww.textfield labelKey="com.zend.zendserver.plugins.api_key" name="api_key" required='true'/]
<small>The name of the API key</small>
[@ww.textfield labelKey="com.zend.zendserver.plugins.api_secret" name="api_secret" required='true'/]
<small>The secret/hash of the API key</small>
[@ww.textfield labelKey="com.zend.zendserver.plugins.base_url" name="base_url" required='true'/]
<small>The baseUri of where the application will be installed</small>
[@ww.textfield labelKey="com.zend.zendserver.plugins.app_name" name="app_name" required='true'/]
<small>Name of the application</small>
[@ww.textfield labelKey="com.zend.zendserver.plugins.zsversion" name="zsversion" required='true'/]
<small>The major Zend Server version. Ex: 6.0, 6.1, 6.3</small>
[@ww.textfield labelKey="com.zend.zendserver.plugins.userparams" name="userparams" required='false'/]
<small>User parameters that have to be formated as a query string</small>
[@ww.textfield labelKey="com.zend.zendserver.plugins.customzpk" name="customzpk" required='false'/]
<small>Optionally a path to a custom ZPK file can be specified. If the field remains empty, the Deployment task type tries to grab a ZPK generated by the Packaging Task.</small>