[@ww.label labelKey="Zend Server URL" name="zs_url"/]
[@ww.label labelKey="API Key" name="api_key"/]
[@ww.label labelKey="API Secret" name="api_secret"/]
[@ww.label labelKey="Application Base URL" name="base_url"/]
[@ww.label labelKey="Application Name" name="app_name"/]
[@ww.label labelKey="Zend Server Version" name="zsversion"/]
[@ww.label labelKey="Amount of retries for status check" name="retry"/]
[@ww.label labelKey="Wait time (sec) between retry iterations" name="waittime"/]